julianharr/lumina

Gemfile
Gemfile.lock
app/controllers/favourite_events_controller.rb
app/models/chatroom.rb
app/models/favorite.rb
app/models/favourite.rb
config/initializers/acts_as_favoritor.rb
config/routes.rb
db/migrate/20210218083741_create_favourites.rb
db/migrate/20210218100402_add_other_user_to_chatrooms.rb
db/migrate/20210218103314_acts_as_favoritor_migration.rb
db/schema.rb

Check it out,
All routes and some edits to the models.
Added Favoritor!
Thanks bros,
Tom

Lumina routes

---

app/assets/stylesheets/components/landing_page/_container-banner.scss
app/views/components/landing_page/_container-banner.html.erb
app/views/components/landing_page/_landing-navbar.html.erb

Updated styling for navbar on the landing page, updated email form

updated navbar on landing page

---

app/models/user.rb
db/seeds.rb

• Added constant named INTERESTS to the User model so list of interests is available for any user
• No updates to Seed file just yet - will work on this on Sunday
Have a good weekend y'all

added constant INTERESTS to User model for list of interests

---

app/assets/stylesheets/application.scss
app/controllers/pages_controller.rb
app/models/user.rb
app/views/devise/sessions/new.html.erb
db/seeds.rb

Hey wanted to work a bit on the app tonight but was bottle-necked by a login page thanks to devise!
Only managed to do some positioning on the login form.
Cheers,
Tom

Some very subtle changes

---

Gemfile
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_side_bar.scss
app/controllers/charities_controller.rb
app/controllers/events_controller.rb
app/controllers/pages_controller.rb
app/policies/application_policy.rb
app/policies/user_policy.rb
app/views/charities/index.html.erb
app/views/components/landing_page/_landing-navbar.html.erb
app/views/events/index.html.erb
app/views/layouts/application.html.erb
app/views/messages/index.html.erb
app/views/pages/dashboard.html.erb
app/views/pages/feed.html.erb
config/routes.rb
test/controllers/charities_controller_test.rb

Hey guys,
Did a bit of work on this tonight. Was finally able to get into the app with the update to the seed file (thanks C). Created a basic skeleton between the feed and other pages. Added a few new component files and added the Devise Policy folders.. for some reason, I couldn't quite make "authorize" work on the controllers tonight but can look at it later.
Also added a log-out button on the landing page as I was having issues. Obviously can be removed. Oh, and I added the CSS link to Bootstrap 5, not 100% if it works (Gemfile wouldn't bundle install or with the direct command) but had a play about with BS and read some documentation.
Cheers homies,
Tom

created links between pages amongst other small tasks

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/landing_page/_container-banner.scss
app/assets/stylesheets/components/landing_page/_container-landing-bottom.scss
app/assets/stylesheets/components/landing_page/_container-landing-info.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/components/landing_page/_container-banner.html.erb
app/views/components/landing_page/_container-landing-bottom.html.erb
app/views/components/landing_page/_container-landing-info.html.erb
app/views/components/landing_page/_landing-navbar.html.erb

• Fixed issue with page responsiveness and image warping
• Adjusted font colours for bootstrap variables
• Added 'glow' effect for sign up buttons and for middle container
• Minor margin/padding tweaks
Thanks fellas

Front end updates to landing page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/charities_page/_charity_cards.scss
app/assets/stylesheets/components/charities_page/_charity_page.scss
app/assets/stylesheets/components/charities_page/_loading_animation.scss
app/javascript/packs/application.js
app/views/charities/index.html.erb
app/views/components/charities_page/_infinite_scroll.html.erb

• Added infinite scroll feature to charity page we can implement in our feed
• Stying of the cards for charity page
https://user-images.githubusercontent.com/62631835/108798825-d5811f80-75e2-11eb-9751-d2dffb2a57ce.mov

Added infinite scroll feature to Charity page

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/interests_page/_interests_cards.scss
app/controllers/interests_controller.rb
app/controllers/pages_controller.rb
app/javascript/packs/application.js
app/views/pages/interests.html.erb
config/routes.rb

Image selection is then sent through to the params and made into an array in the interests controller.
Check the Javascript
BAM

Added /interests page where user can select images

---

app/assets/stylesheets/components/_index.scss
app/channels/chatroom_channel.rb
app/controllers/chatrooms_controller.rb
app/controllers/messages_controller.rb
app/controllers/pages_controller.rb
app/javascript/channels/chatroom_channel.js
app/javascript/packs/application.js
app/models/chatroom.rb
app/models/item.rb
app/models/message.rb
app/models/user.rb
app/views/chatrooms/index.html.erb
app/views/chatrooms/show.html.erb
app/views/components/feed_page/_chat_modal.erb
app/views/components/side_bar/_side_bar_final.html.erb
app/views/messages/_message.html.erb
app/views/pages/feed.html.erb
config/environments/development.rb
config/routes.rb
test/channels/chatroom_channel_test.rb

Hey fellas - added basic setup for the chat functionality. I've resolved a conflict in the Pages Controller already so should be good to merge to master.
Take a look when you can. Thanks.

Updates to Chat - still a work in progress

---

app/controllers/application_controller.rb
app/controllers/interests_controller.rb
app/controllers/registrations_controller.rb
app/controllers/users_controller.rb
app/views/devise/registrations/new.html.erb
app/views/pages/interests.html.erb
config/routes.rb

Have now set up interests.
New user created  page will redirect => interests page
interests page with redirect to => feed upon selecting interests
The interests array can be accessed with @user.interest_list for the users afterword
Had to create a new controller for devise for the redirect after sign up.
Phew.
Cheers boys

Interests set up complete

---

app/models/event.rb
db/migrate/20210227011011_add_event_time_to_events.rb
db/migrate/20210227011836_add_utc_offset_to_events.rb
db/migrate/20210227030904_change_date_to_events.rb
db/schema.rb
db/seeds.rb
db/seeds_api.rb

seeds file updated and generating events for Tech in MELB only
you need to Un comment out to unleash the beast
need : db:migrate

Api saturday

---

app/controllers/chatrooms_controller.rb
app/controllers/messages_controller.rb
app/controllers/pages_controller.rb
app/views/chatrooms/index.html.erb
app/views/chatrooms/show.html.erb
app/views/pages/feed.html.erb
config/routes.rb
db/schema.rb

Fellas - 
• Chat is working.
• Julian is happy.

Chat Works.

---

app/controllers/chatrooms_controller.rb
app/views/chatrooms/index.html.erb
app/views/chatrooms/show.html.erb
app/views/components/side_bar/_side_bar_final.html.erb
app/views/messages/_message.html.erb
app/views/pages/feed.html.erb
db/schema.rb

• Added avatar for chat
• Chats reflect in real time on each users profiles

Chat works between two users in real time

---

config/environments/production.rb

production test

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/controllers/events_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/models/event.rb
app/views/components/side_bar/_side_bar_final.html.erb
app/views/events/index.html.erb
app/views/pages/feed.html.erb
config/initializers/geocoder.rb
package.json
yarn.lock

Added a basic map with Mapbox

---

config/environments/production.rb
config/routes.rb

Testing updates for deployment to heroku for actioncable

testing redis updates for heroku

---

db/seeds.rb

no friends

---

db/migrate/20210302092214_add_event_time_to_events.rb
db/schema.rb

update migration files so TT can get PAID

---

app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/components/_side_bar.scss

added sticky side bar and map

---

app/assets/stylesheets/components/_side_bar.scss
app/views/components/side_bar/_side_bar_final.html.erb
app/views/pages/feed.html.erb

Sign out from anywhere

---

app/views/components/side_bar/_side_bar_final.html.erb

• Friends modal moved outside of sidebar div to work again

friends modal working

---

app/controllers/events_controller.rb
app/views/events/show.html.erb
app/views/pages/feed.html.erb

added button for events and slight show page

---

app/views/friends/index.html.erb

minor styling updates to friend page

---

app/views/pages/feed.html.erb

slight update

---

app/assets/stylesheets/application.scss
app/javascript/packs/application.js

fixed MAPBOX CSS import for webpack

---

app/views/components/side_bar/_side_bar_final.html.erb

fixed user sign OUT

---

app/controllers/events_controller.rb
app/controllers/pages_controller.rb
app/models/user.rb
app/views/pages/feed.html.erb
db/migrate/20210306032422_add_host_name_to_events.rb
db/schema.rb
db/seeds.rb
db/seeds_api.rb

events relate to the users interests

feed with events for user

---

app/controllers/registrations_controller.rb
app/controllers/users_controller.rb
app/views/components/side_bar/_side_bar_final.html.erb
app/views/devise/registrations/new.html.erb

Hello,
I've added some extra fields to registration. These include name, birthday, and an image (that will hopefully work as an avatar on the user).
I still need to work out how to choose a specific date when signing up, 1931 doesn't seem too accurate for our client base but hey, we cater to all ages here at Lumina.
Cheers,
Tom

Added extra fields to Registration

---

app/controllers/pages_controller.rb
app/controllers/statuses_controller.rb
app/models/status.rb
app/views/pages/feed.html.erb
config/routes.rb
db/migrate/20210306010905_create_statuses.rb
db/schema.rb
test/controllers/statuses_controller_test.rb
test/models/status_test.rb

Basic status update logic created

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/events_page/_events.scss
app/views/events/index.html.erb
app/views/pages/feed.html.erb

• Update styling for Events Page

events page styling updated

---

app/controllers/statuses_controller.rb
app/views/pages/feed.html.erb

Made AJAX work on statuses

---

app/controllers/pages_controller.rb
app/views/components/side_bar/_side_bar_final.html.erb

Still some bug fixes with feed but fixed sidebar

sidebar and feed fix temp

---

Gemfile

moved web console gem outside of development group in gemfile

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/friends_page/_friends.scss
app/views/friends/index.html.erb

• Big front end style and logic changes to Friends page.
• Added messaging button for existing friends
• Only people with common interests show up in your Meet Someone New section
• 'Meet Someone New' section includes mutual interests

Friends logic and style update

---

app/assets/stylesheets/components/_side_bar.scss
app/views/components/side_bar/_side_bar_final.html.erb

Updated spacing and alignment for sidebar

Sidebar update march8

---

app/assets/stylesheets/components/friends_page/_friends.scss
app/views/friends/index.html.erb

• Not entirely sure if the Seedfile issue has been resolved or not but let's hope so
• Changed font-size on friends cards
• Added span class to style individual interests on the strangers card

changed colour and font size for friends page

---

Gemfile.lock
app/controllers/users/omniauth_callbacks_controller.rb
app/models/service.rb
config/environments/development.rb
config/initializers/devise.rb

Oauth Setup
- facebook
- meetup
Will need to push to HEROKU pls

Oauth setup

---

app/controllers/users/omniauth_callbacks_controller.rb
app/models/service.rb
config/initializers/devise.rb

oauth meetup3

---

app/assets/stylesheets/components/friends_page/_friends.scss
app/views/components/friends_page/_friend_card.html.erb
app/views/components/friends_page/_stranger_card.html.erb

• Font and images had not been updated in the modals yet. 
• Fixed this issue

fixed font size and image size on friends page

---

app/assets/stylesheets/components/_side_bar.scss
app/views/components/side_bar/_side_bar_final.html.erb

Added active class to sidebar

---

app/assets/stylesheets/components/_feed_card.scss
app/assets/stylesheets/components/_side_bar.scss
app/assets/stylesheets/components/events_page/_events.scss
app/controllers/events_controller.rb
app/javascript/packs/application.js
app/views/components/dashboard_page/_dashboard_modal.html.erb
app/views/components/side_bar/_side_bar_final.html.erb
app/views/devise/registrations/new.html.erb
app/views/events/show.html.erb
app/views/pages/dashboard.html.erb
db/migrate/20210310072207_change_description_to_string.rb
db/schema.rb

Event show page mainly done
• Once merged please run rails db:migrate
• Still need to fix event description

Event show page

---

app/controllers/wishlists_controller.rb
app/javascript/packs/application.js
app/views/components/feed_page/_add_friends.html.erb
app/views/components/feed_page/_feed_randomising.html.erb
app/views/components/feed_page/_popular_event_categories.html.erb
app/views/pages/feed.html.erb
app/views/wishlists/show.html.erb
test/controllers/wishlists_controller_test.rb

Hello,
Moved "friends in common" off the feed and put it on the left. Added have you seen wishlist? (the link needs to updated, also styling).
Ta

Some updates to feed

---

app/views/components/feed_page/_feed_randomising.html.erb
app/views/pages/feed.html.erb

Unfortunately, the logic for these hearts includes an extra table & more time than I have this morning.
At least people will get the gist (see what I did there) in the demo. I Will try to implement it tonight before the pitch,
Tom

Added heart (with no logic) to statuses

---

app/views/pages/feed.html.erb

• Updated the status card for the feed
• Updated status input section
• Still an issue where style is not applying to all statuses - @Tom-Tee can you please have a look at this when you get a moment

feed style changes

---

app/views/components/feed_page/_add_friends.html.erb
app/views/pages/feed.html.erb

• Adjusted styling on 'Strangers' card for feed

fixed meet someone new styling on feed

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/charities_page/_donate_animation.scss
app/javascript/dom/donate.js
app/javascript/packs/application.js
app/views/components/charities_page/_infinite_scroll.html.erb
app/views/users/show.html.erb

• Hoping this does not cause error with any other JS on the page. Found from a Codepen, tweaked, credited and implemented onto our site.
• Still need to update feed when user clicks on any of these buttons!!
https://user-images.githubusercontent.com/62631835/110739886-23a24e00-8286-11eb-92d6-f485356e1975.mov

Feed style update 11march

---

app/assets/stylesheets/components/chatrooms_page/_chatrooms.scss
app/assets/stylesheets/components/chatrooms_page/_messages.scss
app/views/chatrooms/_show.html.erb
app/views/chatrooms/index.html.erb
app/views/messages/_message.html.erb

more styling chatroom

---

app/javascript/packs/application.js
app/views/components/feed_page/_feed_randomising.html.erb
app/views/pages/feed.html.erb

SOS SAVE THE FEED

---

app/views/components/feed_page/_add_friends.html.erb

fix meet someone new send friend request link

add friend not current_user

---

app/controllers/pages_controller.rb
app/javascript/packs/application.js
app/views/components/feed_page/_feed_randomising.html.erb
app/views/pages/ajax.html.erb
app/views/pages/feed.html.erb
app/views/pages/interests.html.erb
config/routes.rb

We now have an infinite feed with AJAX, always randomised :)
Tom

Trying to ajax? more like ajaxed the feed!!

---

app/controllers/users/omniauth_callbacks_controller.rb
config/environments/development.rb
config/initializers/devise.rb
db/seeds_api.rb

Yo,
Meetup and facie login now works with import of avatar aswell
Still going on events signup :|
C

meetup and facie login now WORKS !!

---

app/controllers/chatrooms_controller.rb
app/controllers/messages_controller.rb
app/models/chatroom.rb
app/models/message.rb
app/views/chatrooms/_show.html.erb
app/views/chatrooms/index.html.erb
app/views/chatrooms/show.html.erb
app/views/messages/_message.html.erb

Quite a bit of work done on this, check the code files if you would like to learn more about proper configuration of a chatroom

Chat style update

---

app/assets/stylesheets/components/_feed_card.scss
app/controllers/donates_controller.rb
app/controllers/pages_controller.rb
app/javascript/packs/application.js
app/views/components/charities_page/_charities_modal.html.erb
app/views/components/charities_page/_infinite_scroll.html.erb
app/views/components/feed_page/_charity_card.html.erb
app/views/components/feed_page/_feed_randomising.html.erb
test/controllers/donates_controller_test.rb

..as LONG as there is no donate currently on that user.
yay!

Donate now posts to feed

---

app/views/components/feed_page/_feed_randomising.html.erb

fixed some feed issues - still need to adjust margin and width of feed page

fixed feed issue

---

app/views/components/feed_page/_feed_randomising.html.erb
db/migrate/20210313045000_add_attending_to_events.rb
db/schema.rb

Updated so it's always the most recent donate that will be on the feed.

Updated recent donate

---

app/models/user.rb
app/views/components/feed_page/_feed_randomising.html.erb

To make seed file work

---

app/assets/stylesheets/components/events_page/_events.scss
app/assets/stylesheets/components/friends_page/_friends.scss
app/controllers/chatrooms_controller.rb
app/controllers/messages_controller.rb
app/views/chatrooms/index.html.erb
app/views/components/charities_page/_charities_modal.html.erb
app/views/components/feed_page/_feed_randomising.html.erb
app/views/components/friends_page/_friend_card.html.erb
app/views/components/friends_page/_stranger_card.html.erb
app/views/components/side_bar/_side_bar_final.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/pages/dashboard.html.erb
app/views/users/show.html.erb
db/schema.rb

Hi everyone
• Updated messages so there is no 'show' page, just an index with people and threads
• Style updates for event page
• Style update for event show page
• Style update for margin on friends page
Issues:
If you want to continue a conversation with someone, you need to go back into your messages at the moment. Need to route it to the existing message thread if there is one...
Thanks :)

Lumina style updates

---

app/controllers/messages_controller.rb

• Message was not going to the bottom of message container

changed it back to how it was

---

db/seeds.rb

not needed

---

app/controllers/users/omniauth_callbacks_controller.rb
config/environments/development.rb
db/schema.rb

updated meetup email to random

updated meetup email to random

---

app/assets/stylesheets/components/chatrooms_page/_messages.scss
app/views/chatrooms/_show.html.erb
app/views/chatrooms/_show_new.html.erb
app/views/chatrooms/index.html.erb
app/views/messages/_message.html.erb

Should be safe to merge. Thank you.

Chat thread update

---

app/assets/stylesheets/components/_feed_card.scss
app/assets/stylesheets/components/_side_bar.scss
app/assets/stylesheets/components/charities_page/_charity_cards.scss
app/views/components/charities_page/_infinite_scroll.html.erb
app/views/components/feed_page/_feed_randomising.html.erb
app/views/components/side_bar/_side_bar_final.html.erb

• Styling update for Charity card on feed
• Styling update for Donation card on feed
https://user-images.githubusercontent.com/62631835/111244313-c415bb00-8656-11eb-9400-3f1c41ed93cd.mov

Updates to Charity and Donate feed cards

---

app/views/components/landing_page/_landing-navbar.html.erb
app/views/components/side_bar/_side_bar_final.html.erb

• Landing page now has option to navigate to your Feed if signed in
• Lumina sidebar logo now takes you to Landing page
• Changed font sizes of Landing Page Nav Options / Added border to 'Log Out' button

Landing page and Sidebar updates

---

db/seeds.rb

• Events are now **tech, pets, environment**
• Status updates no longer Yoda quotes - Famous Last Words quote

updated events to match demo interests

---

app/controllers/application_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/events/show.html.erb
config/environments/development.rb

Yo,
click => login with meetup redirects to same page
C

Oauth interests

---

app/views/components/side_bar/_side_bar_final.html.erb
app/views/pages/dashboard.html.erb
app/views/shared/_friends_modal.html.erb
db/seeds.rb

styling for friends, updated seed file

---

app/assets/stylesheets/components/charities_page/_charity_cards.scss
app/javascript/packs/application.js
app/views/chatrooms/_show_new.html.erb
app/views/components/charities_page/_infinite_scroll.html.erb

Needed to wrap the feedCard in an if-statement
Needed to add remote: true to the chat b/c it was refreshing upon each message send!

javascript fix for chat and feed card

---

app/assets/stylesheets/components/friends_page/_friends.scss
app/views/components/friends_page/_friend_card.html.erb
app/views/friends/index.html.erb

change dropdown menu item list for your friends page

---

app/views/components/charities_page/_infinite_scroll.html.erb
app/views/users/show.html.erb

If User doesn't have a nickname or a bio, replace with what I've written in here

style update for dashboard

---

db/seed_items.rb

Goooooood morning Lumina,
Before I go "working 9 to 5 what a way to make a living";
I've now set up the seed file so that every wishlist will have the same 5 items...
***WARNING* this now makes the seed file TWICE as long to run, so use with caution**. If you would like to run the seed file as before then comment out the wishlist_id in items and remove the iteration.
Thanks muchly,
Tom

Added the same items to every Wishlist

---

app/assets/stylesheets/components/_heart_like.scss
app/views/pages/feed.html.erb
db/seed_items.rb

Slight update to style on user status.
Cheers,

Fixed heart on user status

---

app/assets/stylesheets/components/chatrooms_page/_chatrooms.scss
app/assets/stylesheets/components/chatrooms_page/_messages.scss
app/controllers/chatrooms_controller.rb
app/views/chatrooms/_show_new.html.erb
app/views/chatrooms/index.html.erb
app/views/messages/_message.html.erb

Lots of updates to conversations.
• Conversations are all the same colour now
• Aligned style of each individual message
• Fixed and updated styling for message threads
• You won't see your own name in the message thread anymore
• 'Active' class added to threads you're currently in, with a white border surrounding the image to indicate this
• Local times added to any time we see on the page
• Threads have message previews and last updated below names of person you are messaging

lots of styling update to chats, message threads, etc.

---

app/assets/stylesheets/components/_feed_card.scss
app/assets/stylesheets/components/chatrooms_page/_messages.scss
app/views/events/index.html.erb

font weight change for messaging, add style to search bar for events

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_feed_card.scss
app/assets/stylesheets/pages/_lightmode.scss
app/javascript/dom/themeswitcher.js
app/javascript/packs/application.js
app/views/components/feed_page/_add_friends.html.erb
app/views/components/feed_page/_feed_randomising.html.erb
app/views/pages/feed.html.erb

Light mode for feed has been implemented. Bit of an Easter egg right now...
• Click the small button across from where it says 'Feed' to activate :) 
• Page is responsive for larger screen widths

Feed responsiveness styling

---

app/assets/stylesheets/components/_feed_card.scss
app/views/chatrooms/_show_new.html.erb
app/views/chatrooms/index.html.erb
app/views/components/feed_page/_add_friends.html.erb
app/views/components/side_bar/_side_bar_final.html.erb
app/views/pages/feed.html.erb
db/seed_items.rb
db/seeds.rb

Yo! Updated the feed to look a bit better for the Demo.
Please don't adjust width of anything at the moment. Still a bit more to fiddle with. Thanks!

feed reponsiveness updates for demo

---

app/controllers/events_controller.rb
app/javascript/dom/themeswitcher.js
app/javascript/packs/application.js
app/javascript/plugins/init_autocomplete.js
app/views/events/index.html.erb
app/views/pages/feed.html.erb

i didn't do the PG search stuff left that for TTemple if he wants to sort that 
add a catch to the theme switched to stop errors on other pages 
`if (themeSwitch) {`

places added

---

app/views/components/landing_page/_landing-navbar.html.erb
app/views/devise/registrations/edit.html.erb

updated styling for edit user page

---

app/views/events/show.html.erb

Subtle changes to spelling and changed button width to 50%

spelling update

---

app/javascript/channels/chatroom_channel.js
app/javascript/dom/chatwindow.js
app/javascript/packs/application.js
app/views/chatrooms/_show_new.html.erb
app/views/chatrooms/index.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/users/show.html.erb

• Added JS that keeps chat window at bottom of window on each page reload AND when someone sends a new message
• Added Navigation Options to Sign in/Sign Up forms
• Fixed an issue where the most recent message preview did not give the most recent message send time
• Adjusted (temporarily) the Friends Show page. You can now view anyone's Wishlist if you are not friends with them.

Add JS for Chat Window, Friends Wishlist, Nav Options for Sign in/Sign Up

---

app/controllers/pages_controller.rb

updated pages controller so you don't need to sign in to view

update about page so you don't need to sign in to view

---

app/assets/stylesheets/pages/_lightmode.scss
app/views/components/side_bar/_side_bar_final.html.erb

update colour of light mode background

change bg colour to darker grey on lightmode theme switch

---

app/assets/stylesheets/components/_feed_card.scss
app/assets/stylesheets/components/_side_bar.scss
app/assets/stylesheets/components/landing_page/_container-banner.scss
app/assets/stylesheets/components/landing_page/_container-landing-bottom.scss
app/assets/stylesheets/components/landing_page/_container-landing-info.scss
app/assets/stylesheets/components/signup_page/_signup.scss
app/views/components/side_bar/_side_bar_final.html.erb
app/views/devise/registrations/new.html.erb
app/views/pages/feed.html.erb

Begin post-Le Wagon process of making Lumina responsive for mobile

Make lumina responsive

---

app/views/components/landing_page/_landing-navbar.html.erb

• Removed broken 'About' link until page is updated

remove broken about link

---

app/assets/stylesheets/components/_side_bar.scss
app/views/components/side_bar/_side_bar_final.html.erb

• Fixed issue where nav links on mobile were not responsive
• Temporary addition of vertical navigational bar for mobile on the feed page
• Reduced font sizes for nav links to suit mobile and tablet screen sizes
• Began removing inline Bootstrap styling in .erb files as they took precedence over any written CSS

Responsive styling - feed
